### ISSUE TITLE
Water temperature is incorrect on Remeha Tzerra Ace 24C

### ISSUE THREAD

**Issue by KoosH1951** [ChrisTerBeke/homey-remeha#2]
Chris,
First of all thank you for creating the Remeha Home app.

However I noticed that the watertemperature is incorrect on Remeha Tzerra Ace 24C

![Screenshot_20240509_162020_Remeha Home](https://github.com/ChrisTerBeke/homey-remeha/assets/98040011/f6e981ed-944d-4d5e-826a-b9791a56ba74)

![Schermafbeelding 2024-05-09 162548](https://github.com/ChrisTerBeke/homey-remeha/assets/98040011/a5ea4587-9fe9-41ea-9a4a-84e58e66455e)

![Schermafbeelding 2024-05-09 162637](https://github.com/ChrisTerBeke/homey-remeha/assets/98040011/0f6fdb56-f6e9-4f8e-a1d5-19a8ed1d60ed)

Please let me know when you need additional info.

**Comment by ChrisTerBeke** [comment]
Hi,

Can you confirm whether 58 is the actual temperature or target temperature of the hot water? Because for me, this page in the Remeha Home app shows the target temperature inside the big circle, and the actual temperature is on the top left. I doubt the API property is suddenly different on your Tzerra Ace.

![image](https://github.com/ChrisTerBeke/homey-remeha/assets/1134120/fc6ad5f7-dee7-4577-b6e5-6c021814aff8)

**Comment by KoosH1951** [comment]
Chris,

The Remeha Homey app does not show in my case the actual temperature, strange but so be it. 

I checked the he temperature in Insights and there the highest value is 58, which is the target temperature and is decreasing to 28. 
So your values are correct
This has to do with the fact that the Eco mode has been selected.

So no bug.
Thanks.

**Comment by ChrisTerBeke** [comment]
Thanks for checking! I see similar values in my temperature history (heating up to the target, then slowly decreasing over time to a minimum of around 30 degrees, then back up).
